name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            asset_name: rusttpx-x86_64-unknown-linux-gnu
          - os: macos-latest
            target: x86_64-apple-darwin
            asset_name: rusttpx-x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
            asset_name: rusttpx-aarch64-apple-darwin

    steps:
      - uses: actions/checkout@v4
      
      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          override: true
      
      - name: Build
        run: |
          cargo build --release --features cli --target ${{ matrix.target }}
      
      - name: Create release asset
        run: |
          cp target/${{ matrix.target }}/release/rusttpx ${{ matrix.asset_name }}
      
      - name: Upload release asset
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.asset_name }}
          path: ${{ matrix.asset_name }}

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: ./artifacts
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Release ${{ github.ref }}
            
            ## Binaries
            - `rusttpx-x86_64-unknown-linux-gnu` - Linux x86_64
            - `rusttpx-x86_64-apple-darwin` - macOS x86_64
            - `rusttpx-aarch64-apple-darwin` - macOS ARM64
          draft: false
          prerelease: false
      
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/rusttpx-x86_64-unknown-linux-gnu/rusttpx-x86_64-unknown-linux-gnu
          asset_name: rusttpx-x86_64-unknown-linux-gnu
          asset_content_type: application/octet-stream
      
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/rusttpx-x86_64-apple-darwin/rusttpx-x86_64-apple-darwin
          asset_name: rusttpx-x86_64-apple-darwin
          asset_content_type: application/octet-stream
      
      - name: Upload Release Assets
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./artifacts/rusttpx-aarch64-apple-darwin/rusttpx-aarch64-apple-darwin
          asset_name: rusttpx-aarch64-apple-darwin
          asset_content_type: application/octet-stream
